### ISSUE TITLE
ringbuf 0.4.3 breaks dependants calling `SharedRb::new`

### ISSUE THREAD

**Issue by GnomedDev** [agerasev/ringbuf#37]
songbird 0.4.3 no longer compiles as it is simply calling `SharedRb::new` which is now ambiguous between `ringbuf::SharedRb<Heap<T>::new` and `ringbuf::SharedRb<Owning<[MaybeUninit<T>; N]>>`. The full error is
```
error[E0034]: multiple applicable items in scope
   --> /home/lothrop/.cargo/git/checkouts/songbird-bfb5fd0fe254c2b1/8f66320/src/input/adapters/async_adapter.rs:159:47
    |
159 |         let (bytes_in, bytes_out) = SharedRb::new(buf_len).split();
    |                                               ^^^ multiple `new` found
    |
    = note: candidate #1 is defined in an impl for the type `ringbuf::SharedRb<Heap<T>>`
    = note: candidate #2 is defined in an impl for the type `ringbuf::SharedRb<Owning<[MaybeUninit<T>; N]>>`
```

The line quoted is https://github.com/serenity-rs/songbird/blob/2d7dc29fd68826fb6998eb748be05387ea2fe91b/src/input/adapters/async_adapter.rs#L159 and this was probably caused by 6f637f14cb15614732ae1f8421822a71641a604c.

**Comment by cycle-five** [comment]
+1
https://github.com/cycle-five/cracktunes/actions/runs/10432496012/job/28893244435#step:7:1473

**Comment by agerasev** [comment]
Thank you for your report!

The issue seems to be in [adding a `StaticRb::new` method](https://github.com/agerasev/ringbuf/blob/6f637f14cb15614732ae1f8421822a71641a604c/src/rb/macros.rs#L9-L11). I did not expect that this is a breaking change, sorry.

I've yanked `0.4.2` and `0.4.3`

**Comment by brunowonka** [comment]
Quick FYI here I couldn't find it reported anywhere else. Yanking 0.4.3 seems to break async-ringbuf 0.3.0

```
error: failed to select a version for the requirement `ringbuf = "^0.4.3"`
candidate versions found which didn't match: 0.4.1, 0.4.0, 0.4.0-rc.4, ...
location searched: crates.io index
required by package `async-ringbuf v0.3.0`
    ... which satisfies dependency `async-ringbuf = "^0.3.0"` of package `rust-playground v0.1.0 (/usr/local/google/home/brunodalbo/Documents/git/rust-playground)`
if you are looking for the prerelease package it needs to be specified explicitly
    ringbuf = { version = "0.4.0-rc.4" }
```

https://crates.io/crates/async-ringbuf/0.3.0/dependencies

**Comment by agerasev** [comment]
> Quick FYI here I couldn't find it reported anywhere else. Yanking 0.4.3 seems to break async-ringbuf 0.3.0

Thanks! I've published ringbuf-0.4.4, it seems to fix this.

**Comment by GnomedDev** [comment]
Magic, can't ask for any response better!
